apiVersion: v1
kind: Secret
metadata:
  name: argo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  project: default
  name: Argo
  url: https://argoproj.github.io/argo-helm