apiVersion: v1
kind: Secret
metadata:
  name: harbor-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://helm.goharbor.io
  name: harbor-helm
  type: helm