apiVersion: v1
kind: Secret
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://kubernetes-sigs.github.io/metrics-server/
  name: Metrics Server
  type: helm