apiVersion: v1
kind: Secret
metadata:
  name: sealedsecrets
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  project: default
  name: SealedSecrets
  url: https://bitnami-labs.github.io/sealed-secrets